adminUser:
  password: vault:pr-369-4arc/adminUser:password
  username: admin
dashboardAuthID: vault:pr-369-4arc:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:pr-369-4arc:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-369-4arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-369-4arc/prow:hmacToken
